### ISSUE TITLE
Ignore messages in group chats that don't look like transactions

### ISSUE THREAD

**Issue by Fawerki** [LucaBernstein/beancount-bot-tg#190]
- Ignore everything that is sent in a group chat outside a transaction
- Exceptions: Numbers to start a transaction and messages starting with /, indicating commands

Background: Allow to use a group chat with beancount bot for communication

**Comment by LucaBernstein** [comment]
Thanks for your idea. I also once thought around something similar. Maybe that's finally the reason to implement it: #169

**Comment by LucaBernstein** [comment]
Dear @Fawerki your issue has been implemented and has just been published. Take a look: https://github.com/LucaBernstein/beancount-bot-tg/releases/tag/v0.22.0
