### ISSUE TITLE
Unable to record cash-in transaction

### ISSUE THREAD

**Issue by xentac** [LucaBernstein/beancount-bot-tg#228]
**Describe the bug**
I had someone give me money and I wanted to record it in beancount. I wasn't able to figure out how to add Cash to my wallet instead of remove it.

**To Reproduce**
1. Create a transaction, with an amount of `10`, from Assets:Cash to some Expense account. The transaction will be -10 Units.
2. Create a transaction, with an amount of `-10`, from Assets:Cash to some Expense account. The transaction will be -10 Units.

**Expected behavior**
One of those two options should let me add money to Cash. One might consider it an accounts:to, but then I'm just listing all my accounts in both accounts:from and accounts:to

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LucaBernstein** [comment]
Hi [xentac](https://github.com/xentac), thank you for your issue!

I checked on your report and I see the problem.

I will change the logic accordingly, as I cannot see any blockers not to do so (changes a bit the current behaviour, but should be manageable).

PR: https://github.com/LucaBernstein/beancount-bot-tg/pull/229
